version: "3.8"

services:
  db:
    image: mysql
    container_name: test_hv_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/data/:/home/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hv
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: test_hv_phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 3000000000
    networks:
      - dev

  www:
    build: '.docker/php'
    container_name: test_hv_www
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./.docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev

networks:
    dev:

volumes:
    db-data: